import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
        width:"100%",
        height:"25%",
    },
    head:{
        width:"100%",
        height:50,
        flexDirection:"row",
        alignItems:"center",
        // justifyContent:"space-between",
        paddingHorizontal:"4%"
    },
    title:{
        fontSize:18,
        fontFamily:"Poppins-Medium",
        color:"black",
        marginLeft:"25%"
    },
    itemContainer:{
        height:38,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-evenly",
        paddingHorizontal:"3%",
        backgroundColor:"#f2f2f2",
        borderRadius:30,
        // width:"45%",
        marginLeft:"2%"
    },
    itemText:{
        fontSize:14,
        fontFamily:"Poppins-Medium",
        color:"black",
    },
    placeInputContainer:{
        width:"100%",
        flexGrow:1,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-evenly",
    },
    customIconView:{
        width:"10%",
        height:"55%",
        alignItems:"center",
        justifyContent:"space-evenly"
    },
    listView:{
        width:"100%",
        flexDirection:"row"
    },
    round:{
        width:8,
        height:8,
        borderRadius:8,
        backgroundColor:"gray"
    },
    line:{
        height:"60%",
        width:1,
        backgroundColor:"black"
    },
    square:{
        width:8,
        height:8,
        borderRadius:1,
        backgroundColor:"black"
    },
    inputView:{
        width:"75%",
        height:"80%",
        alignItems:"center",
    },
    inputContainer:{
        width:"100%",
        height:30,
        backgroundColor:"#f2f2f2",
        marginTop:"2%",
        justifyContent:"center",
        paddingLeft:"5%"
    },
    addButton:{
        width:30,
        height:30,
        borderRadius:30,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#f2f2f2"
    },
    textInput:{
        fontSize:16,
        fontFamily:"Poppins-Medium"
    }
});

export default styles